language: python
python:
    - "3.2"
env:
    - BUILD_ENV=TravisCI
install:
    - "pip install -r server/requirements.txt --allow-external xively-python"
script:
    - ./server/test.py
    - make -C documents/uml
