ARDUINO_DIR      = /Applications/Arduino.app/Contents/Resources/Java
ARDMK_DIR        = ../make_env
AVR_TOOLS_DIR    = $(ARDUINO_DIR)/hardware/tools/avr
MONITOR_PORT     = /dev/ttyACM0
MONITOR_BAUDRATE = 9600
BOARD_TAG        = pro
ARDUINO_LIBS     = SoftwareSerial Wire XBee INA226 Adafruit_INA219 datatype debug

include ../make_env/Arduino.mk
